### ISSUE TITLE
Problem with Nginx proxy manager

### ISSUE THREAD

**Issue by Martin-Fox** [tdjsnelling/sqtracker#74]
Hi!
I wanted to use sqtracker, but I already have NPM, so I don't need (and don't want) traefic.
So my docker-compose.yml looks like that:

```
version: "3.9"
services:
  database:
    container_name: sq_mongodb
    image: mongo:latest
    volumes:
      - ./data:/data/db
    networks:
      - torrent
  api:
    container_name: sq_api
    image: ghcr.io/tdjsnelling/sqtracker-api:latest
    volumes:
      - type: bind
        source: ./config.js
        target: /sqtracker/config.js
    depends_on:
      - database
    networks:
      - torrent
  client:
    container_name: sq_client
    image: ghcr.io/tdjsnelling/sqtracker-client:latest
    volumes:
      - type: bind
        source: ./config.js
        target: /sqtracker/config.js
    depends_on:
      - api
    networks:
      - torrent
networks:
  torrent:
    name: torrent_network
```

As you can see, I'm not exposing any ports outside, everything is using docker network. NPM is in the same network, and it can reach sq_api and sq_client. But when I try to log in I have error **"Could not log in: Failed to fetch"**

Any hint, how reverse proxy should be set up to have it working?
